'use client';
import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Calendar, Clock, User as UserIcon, FileText, CheckCircle, XCircle, Trash2, MapPin, ChevronRight, Video, Activity, Image, X, Download, Shield } from 'lucide-react';
import { Appointment, MedicalFile } from '../types';
import { useRouter } from 'next/navigation';
import { getFilesSharedWithDoctor, updateFileInStorage, saveNotification } from '@/lib/auth';

interface AppointmentListProps {
  appointments: Appointment[];
  role: 'doctor' | 'patient';
  onAction?: (id: string, action: 'confirmed' | 'cancelled' | 'completed') => void;
  sharedFiles?: MedicalFile[];
  onSharedFilesChange?: (updater: (prev: MedicalFile[]) => MedicalFile[]) => void;
}

export default function AppointmentList({
  appointments, role, onAction,
  sharedFiles: controlledFiles,
  onSharedFilesChange,
}: AppointmentListProps) {
  const router = useRouter();
  const [internalFiles, setInternalFiles] = useState<MedicalFile[]>([]);
  const sharedFiles = controlledFiles ?? internalFiles;
  const [activeFileForModal, setActiveFileForModal] = useState<MedicalFile | null>(null);
  const [commentText, setCommentText] = useState('');
  const [isSavingComment, setIsSavingComment] = useState(false);
  const [scanFilter, setScanFilter] = useState<'standard' | 'negative' | 'contrast'>('standard');
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const toastTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = (msg: string) => {
    if (toastTimerRef.current) clearTimeout(toastTimerRef.current);
    setToastMessage(msg);
    toastTimerRef.current = setTimeout(() => {
      setToastMessage(null);
      toastTimerRef.current = null;
    }, 3000);
  };

  useEffect(() => {
    return () => { if (toastTimerRef.current) clearTimeout(toastTimerRef.current); };
  }, []);

  const updateSharedFiles = useCallback(
    (updater: (prev: MedicalFile[]) => MedicalFile[]) => {
      if (onSharedFilesChange) onSharedFilesChange(updater);
      else setInternalFiles(updater);
    },
    [onSharedFilesChange],
  );

  useEffect(() => {
    if (role === 'doctor' && !controlledFiles) {
      setInternalFiles(getFilesSharedWithDoctor());
    }
  }, [role, controlledFiles]);

  const handleDownloadFile = (file: MedicalFile) => {
    const fileContent = `==================================================
NEXUSHEALTH MEDICAL EHR DOCUMENT VAULT (SECURE DECRYPT)
==================================================
Document ID:     ${file.id}
Document Name:   ${file.name}
Category:        ${file.category}
Uploaded At:     ${new Date(file.uploadedAt).toLocaleString()}
EHR Security:    AES-256 GCM Encrypted
Sharing Status:  SHARED WITH ASSIGNED DOCTOR (DECRYPTED VIEW)

--------------------------------------------------
DOCUMENT DATA DECRYPTION METADATA
--------------------------------------------------
This document has been decrypted securely in-browser from patient EHR vault storage.
For production workloads, this is mapped to a secure cloud S3 storage location.

Generated by NexusHealth CareLoop Core.
==================================================`;
    const url = URL.createObjectURL(new Blob([fileContent], { type: 'text/plain;charset=utf-8' }));
    const element = document.createElement("a");
    element.href = url;
    element.download = file.name.replace(/\.[^/.]+$/, "") + "_decrypted.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    URL.revokeObjectURL(url);
  };

  const handleSaveComment = async () => {
    if (!activeFileForModal || isSavingComment) return;
    const targetId = activeFileForModal.id;
    const savedComment = commentText;
    const fileSnapshot = activeFileForModal;
    setIsSavingComment(true);
    try {
      await new Promise(r => setTimeout(r, 600));
      const updatedFile = { ...fileSnapshot, doctorComments: savedComment };
      updateFileInStorage(updatedFile);
      updateSharedFiles(prev =>
        prev.map(f => f.id === targetId ? updatedFile : f)
      );
      if (fileSnapshot.patientId) {
        saveNotification({
          id: `notif-${Date.now()}`,
          userId: fileSnapshot.patientId,
          title: 'Doctor Note Added',
          message: `Your doctor left a clinical note on "${fileSnapshot.name}".`,
          type: 'file_shared',
          read: false,
          createdAt: new Date().toISOString(),
        });
      }
      showToast('Clinical comment saved!');
      setActiveFileForModal(null);
    } finally {
      setIsSavingComment(false);
    }
  };

  const getFileIcon = (category: MedicalFile['category']) => {
    switch (category) {
      case 'Prescription':
        return <FileText className="h-3.5 w-3.5 text-indigo-500" />;
      case 'Lab Result':
        return <Activity className="h-3.5 w-3.5 text-emerald-500" />;
      case 'Scan':
        return <Image className="h-3.5 w-3.5 text-amber-500" />;
      default:
        return <FileText className="h-3.5 w-3.5 text-slate-500" />;
    }
  };

  const renderRangeGauge = (val: number, low: number, high: number, minScale: number, maxScale: number) => {
    const percentage = Math.max(0, Math.min(100, ((val - minScale) / (maxScale - minScale)) * 100));
    const rangeLowPct = ((low - minScale) / (maxScale - minScale)) * 100;
    const rangeHighPct = ((high - minScale) / (maxScale - minScale)) * 100;
    const isOutOfRange = val < low || val > high;

    return (
      <div className="flex flex-col gap-1.5 w-full py-1.5 select-none">
        <div className="relative h-2 bg-panel rounded-full tt">
          {/* Highlighted Normal Range Zone */}
          <div 
            className="absolute h-full bg-emerald-500/10 border-x border-emerald-500/20"
            style={{ left: rangeLowPct + "%", right: (100 - rangeHighPct) + "%" }}
          />
          {/* Current Value Marker Pin */}
          <div 
            className={`absolute -top-1 w-4 h-4 rounded-full border-2 border-white shadow-md flex items-center justify-center ${
              isOutOfRange ? 'bg-rose-500 ring-4 ring-rose-500/15' : 'bg-emerald-500 ring-4 ring-emerald-500/15'
            }`}
            style={{ left: percentage + "%", transform: 'translateX(-50%)' }}
            title={`Value: ${val} (Ref Range: ${low} - ${high})`}
          >
            {isOutOfRange && (
              <span className="absolute w-2.5 h-2.5 rounded-full bg-white animate-ping opacity-75" />
            )}
          </div>
        </div>
        <div className="flex justify-between text-[8px] text-ghost font-bold uppercase tracking-wider leading-none tt">
          <span>Min {minScale}</span>
          <span className="text-ghost font-semibold">Healthy Bounds ({low} - {high})</span>
          <span>Max {maxScale}</span>
        </div>
      </div>
    );
  };

  const renderReportContent = (file: MedicalFile) => {
    switch (file.category) {
      case 'Lab Result':
        return (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black text-slate-400 uppercase tracking-widest">Chemistry Test Metrics</span>
              <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-100 flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                Lab Verified
              </span>
            </div>
            
            <div className="overflow-hidden border border-wire/60 rounded-2xl bg-card shadow-sm p-4 space-y-4 tt">
              <div className="flex flex-col divide-y divide-haze tt">
                {/* Hemoglobin */}
                <div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="min-w-[150px]">
                    <h5 className="text-sm font-semibold text-ink tt">Hemoglobin (Hb)</h5>
                    <p className="text-[10px] text-ghost font-bold uppercase tracking-wider tt">Standard Blood Metric</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-bold text-ink tt">14.2 g/dL</span>
                    <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-lg">Normal</span>
                  </div>
                  <div className="flex-1 max-w-xs w-full">
                    {renderRangeGauge(14.2, 13.8, 17.2, 12.0, 19.0)}
                  </div>
                </div>

                {/* Fasting Blood Sugar */}
                <div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="min-w-[150px]">
                    <h5 className="text-sm font-semibold text-ink tt">Fasting Blood Sugar</h5>
                    <p className="text-[10px] text-ghost font-bold uppercase tracking-wider tt">Glucose Panel</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-bold text-ink tt">95 mg/dL</span>
                    <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-lg">Normal</span>
                  </div>
                  <div className="flex-1 max-w-xs w-full">
                    {renderRangeGauge(95, 70, 100, 50, 120)}
                  </div>
                </div>

                {/* Total Cholesterol */}
                <div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="min-w-[150px]">
                    <h5 className="text-sm font-semibold text-ink tt">Total Cholesterol</h5>
                    <p className="text-[10px] text-ghost font-bold uppercase tracking-wider tt">Lipid Panel</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-bold text-rose-600">218 mg/dL</span>
                    <span className="text-[10px] font-bold text-rose-600 bg-rose-50 border border-rose-100 px-2 py-0.5 rounded-lg font-bold">High</span>
                  </div>
                  <div className="flex-1 max-w-xs w-full">
                    {renderRangeGauge(218, 100, 200, 100, 260)}
                  </div>
                </div>

                {/* WBC */}
                <div className="py-3 flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="min-w-[150px]">
                    <h5 className="text-sm font-semibold text-ink tt">White Blood Cells (WBC)</h5>
                    <p className="text-[10px] text-ghost font-bold uppercase tracking-wider tt">Immune System Metric</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-sm font-bold text-ink tt">6.8 x10³/µL</span>
                    <span className="text-[10px] font-bold text-emerald-600 bg-emerald-50 border border-emerald-100 px-2 py-0.5 rounded-lg">Normal</span>
                  </div>
                  <div className="flex-1 max-w-xs w-full">
                    {renderRangeGauge(6.8, 4.5, 11.0, 2.0, 14.0)}
                  </div>
                </div>
              </div>
            </div>
          </div>
        );

      case 'Scan':
        return (
          <div className="space-y-4">
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest block">Radiology Scan & Findings</span>
            
            {/* Diagnostic Filter Control panel */}
            <div className="flex flex-wrap gap-2">
              {[
                { id: 'standard', label: 'Standard View' },
                { id: 'negative', label: 'Invert View (Negative)' },
                { id: 'contrast', label: 'Pathology Contrast' }
              ].map((f) => (
                <button
                  key={f.id}
                  type="button"
                  onClick={() => setScanFilter(f.id as 'standard' | 'negative' | 'contrast')}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all active:scale-95 border ${
                    scanFilter === f.id
                      ? 'bg-blue-600 border-blue-600 text-white shadow-md'
                      : 'bg-card border-wire text-dim hover:bg-panel tt'
                  }`}
                >
                  {f.label}
                </button>
              ))}
            </div>

            {/* Visual X-ray simulated box */}
            <div className={`relative rounded-2xl aspect-video border overflow-hidden flex items-center justify-center transition-all duration-500 shadow-lg ${
              scanFilter === 'negative' 
                ? 'bg-white border-slate-350 shadow-slate-100' 
                : 'bg-slate-950 border-slate-800 shadow-slate-950/20'
            }`}>
              {/* Scan grid effect */}
              {scanFilter !== 'negative' && (
                <div className="absolute inset-0 bg-[linear-gradient(to_right,#0284c715_1px,transparent_1px),linear-gradient(to_bottom,#0284c715_1px,transparent_1px)] bg-[size:16px_16px] pointer-events-none" />
              )}
              
              {/* Scanner Sweep Line */}
              <div className={`absolute left-0 right-0 h-0.5 pointer-events-none opacity-75 animate-sweep ${
                scanFilter === 'negative' ? 'bg-slate-400' : 'bg-gradient-to-r from-transparent via-sky-400 to-transparent'
              }`} />

              {/* Styles for sweep animation */}
              <style>{`
                @keyframes sweep {
                  0% { top: 0%; }
                  50% { top: 100%; }
                  100% { top: 0%; }
                }
                .animate-sweep {
                  animation: sweep 4s ease-in-out infinite;
                }
              `}</style>
              
              {/* Simple stylized SVG for chest/rib outline to mock an X-Ray */}
              <svg 
                viewBox="0 0 100 60" 
                className={`w-1/2 h-auto filter blur-[0.5px] transition-all duration-500 ${
                  scanFilter === 'negative' 
                    ? 'text-slate-900 opacity-90' 
                    : scanFilter === 'contrast'
                      ? 'text-rose-500 opacity-80 stroke-[2px]'
                      : 'text-sky-400 opacity-45'
                }`} 
                fill="none" 
                stroke="currentColor" 
                strokeWidth="1.5"
              >
                {/* Spine */}
                <path d="M50,5 L50,55" strokeDasharray="2,2" />
                {/* Ribs left */}
                <path d="M50,15 C40,15 35,20 30,28 C25,36 30,42 50,42" />
                <path d="M50,22 C38,22 33,28 28,36 C23,44 28,48 50,48" />
                <path d="M50,29 C36,29 31,35 26,44 C21,52 26,54 50,54" />
                {/* Ribs right */}
                <path d="M50,15 C60,15 65,20 70,28 C75,36 70,42 50,42" />
                <path d="M50,22 C62,22 67,28 72,36 C77,44 72,48 50,48" />
                <path d="M50,29 C64,29 69,35 74,44 C79,52 74,54 50,54" />
                {/* Lungs glow */}
                <ellipse cx="38" cy="32" rx="10" ry="12" fill="currentColor" opacity="0.05" />
                <ellipse cx="62" cy="32" rx="10" ry="12" fill="currentColor" opacity="0.05" />
                
                {/* Pathology anomaly indicator */}
                {scanFilter === 'contrast' && (
                  <>
                    <ellipse cx="38" cy="32" rx="7" ry="9" stroke="#ef4444" strokeWidth="1.5" fill="#ef4444" fillOpacity="0.1" className="animate-pulse" />
                    <line x1="38" y1="20" x2="38" y2="44" stroke="#ef4444" strokeWidth="0.5" strokeDasharray="1,1" />
                    <line x1="26" y1="32" x2="50" y2="32" stroke="#ef4444" strokeWidth="0.5" strokeDasharray="1,1" />
                  </>
                )}
              </svg>

              {/* Pathology Target Labels */}
              {scanFilter === 'contrast' && (
                <div className="absolute top-1/2 left-[12%] -translate-y-1/2 text-[9px] font-mono text-rose-500 bg-rose-950/80 px-2 py-1 rounded border border-rose-500/30 select-none animate-pulse">
                  CRITICAL: HIGHLIGHTED INFILTRATE
                </div>
              )}

              {/* Patient label on X-Ray */}
              <div className={`absolute bottom-3 left-4 text-left font-mono text-[8px] border select-none leading-normal px-2.5 py-1.5 rounded transition-all duration-500 ${
                scanFilter === 'negative'
                  ? 'text-slate-900 bg-slate-100 border-slate-350'
                  : 'text-sky-400 bg-sky-950/80 border-sky-500/20'
              }`}>
                <p>NAME: PATIENT_01_NEXUS</p>
                <p>ID: NEXUS-EHR-7729A</p>
                <p>DATE: {`${new Date(file.uploadedAt).toLocaleDateString()}`}</p>
              </div>

              <div className={`absolute top-3 right-4 text-[9px] font-black tracking-widest border px-2 py-0.5 rounded bg-emerald-950/60 uppercase ${
                scanFilter === 'negative'
                  ? 'text-slate-700 border-slate-400 bg-slate-100'
                  : 'text-emerald-400 border-emerald-400/30'
              }`}>
                Chest AP View
              </div>
            </div>

            {/* Findings report */}
            <div className="bg-panel border border-wire/50 rounded-2xl p-4 text-xs space-y-3 font-semibold text-dim leading-relaxed tt">
              <div>
                <span className="text-[10px] font-black text-ghost block uppercase tracking-wider leading-none mb-1.5 tt">FINDINGS</span>
                <p>Lungs are clear bilaterally. No focal consolidations, effusion, or pneumothorax are seen. Cardiomediastinal contour is normal. The pleural spaces are clear. Bony structures and soft tissues are unremarkable.</p>
              </div>
              <div className="border-t border-wire/50 pt-2.5 tt">
                <span className="text-[10px] font-black text-ghost block uppercase tracking-wider leading-none mb-1.5 tt">IMPRESSION</span>
                <p className="text-ink font-bold tt">No active cardiopulmonary disease. Lungs are clear.</p>
              </div>
            </div>
          </div>
        );

      case 'Prescription':
        return (
          <div className="space-y-4">
            <span className="text-xs font-black text-slate-400 uppercase tracking-widest block">Prescribed Medication Slip</span>
            
            <div className="relative bg-amber-50/40 rounded-2xl p-6 border border-amber-100 shadow-sm overflow-hidden flex flex-col gap-4">
              {/* Safety Watermark Repeating Grid */}
              <div className="absolute inset-0 opacity-[0.03] bg-[radial-gradient(#78350f_1px,transparent_1px)] bg-[size:12px_12px] pointer-events-none" />
              
              {/* Rx watermarked symbol */}
              <div className="absolute top-2 right-4 text-6xl font-serif text-amber-500/10 font-bold select-none">
                ℞
              </div>

              {/* Prescription metadata header */}
              <div className="flex justify-between items-start border-b border-amber-200/40 pb-3 relative">
                <div className="flex items-center gap-2">
                  <div className="w-8 h-8 rounded-lg bg-amber-500/10 flex items-center justify-center border border-amber-500/20 text-amber-800 font-serif font-black text-sm">
                    NH
                  </div>
                  <div className="font-serif italic text-amber-900/80 font-semibold text-sm leading-tight">
                    NexusHealth Cardiology Clinic
                    <span className="block text-[8px] font-sans font-bold uppercase tracking-wider text-slate-400 not-italic mt-0.5">E-PRESCRIBING GATEWAY</span>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-[10px] font-black text-slate-400 uppercase tracking-wider">
                    Ref: Rx-92881
                  </div>
                  <div className="text-[8px] font-bold text-amber-700 bg-amber-100 border border-amber-200 px-1.5 py-0.5 rounded mt-1 inline-block">
                    E-SIGNED: SHA-256
                  </div>
                </div>
              </div>

              {/* Medication details */}
              <div className="space-y-3 font-semibold text-dim text-xs relative tt">
                <div className="flex items-baseline gap-2">
                  <span className="text-base text-amber-800 font-serif font-black">℞</span>
                  <div>
                    <h4 className="text-sm font-black text-ink tt">Lisinopril 10mg</h4>
                    <p className="text-ghost mt-1 tt">Dispense: 30 Tablets (Oral Route)</p>
                  </div>
                </div>

                <div className="bg-white/60 border border-amber-200/20 p-3 rounded-xl space-y-1.5 leading-normal">
                  <p><span className="text-ghost tt">SIG / Instructions:</span> Take 1 tablet daily by mouth in the morning.</p>
                  <p><span className="text-ghost tt">Indication:</span> Hypertension / Blood pressure management</p>
                  <p><span className="text-ghost tt">Refills Allowed:</span> 3 (Three)</p>
                </div>
              </div>

              {/* Doctor signature section */}
              <div className="flex justify-between items-end border-t border-amber-200/40 pt-4 mt-2 relative">
                <div className="text-[8px] text-slate-400 font-bold uppercase leading-none">
                  Digitally Authenticated via EHR Vault<br/>
                  <span className="font-mono text-[7px] text-slate-350">Hash: 8a93d2e...44ff</span>
                </div>
                <div className="text-right">
                  <p className="font-serif italic text-xs text-ink border-b border-wire pb-1 px-4 leading-none tt">Dr. Alexander Smith, MD</p>
                  <p className="text-[9px] text-ghost font-bold uppercase mt-1 leading-none tt">Cardiology Specialist</p>
                </div>
              </div>
            </div>
          </div>
        );
      default:
        return (
          <div className="bg-panel border border-haze rounded-2xl p-4 text-xs font-semibold text-dim tt">
            <p>Document Content Decrypted Successfully. Click Download below to save raw text data.</p>
          </div>
        );
    }
  };

  const getStatusStyles = (status: Appointment['status']) => {
    switch (status) {
      case 'confirmed':
        return 'bg-emerald-50 text-emerald-700 border-emerald-200 ring-emerald-500/10';
      case 'cancelled':
        return 'bg-rose-50 text-rose-700 border-rose-200 ring-rose-500/10';
      case 'completed':
        return 'bg-blue-50 text-blue-700 border-blue-200 ring-blue-500/10';
      default:
        return 'bg-amber-50 text-amber-700 border-amber-200 ring-amber-500/10';
    }
  };

  if (appointments.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-16 px-4 text-center bg-card rounded-2xl border border-dashed border-wire tt">
        <div className="w-20 h-20 bg-panel rounded-full flex items-center justify-center mb-4 tt">
          <Calendar className="h-10 w-10 text-ghost tt" />
        </div>
        <h3 className="text-lg font-semibold text-ink tt">No appointments found</h3>
        <p className="text-dim max-w-xs mx-auto mt-1 tt">
          {role === 'patient' 
            ? "You haven't booked any appointments yet. Start by choosing a doctor."
            : "No appointments scheduled for you at this time."}
        </p>
      </div>
    );
  }

  return (
    <>
      <div className="grid gap-4">
        {appointments.map((appointment) => (
          <div
            key={appointment.id}
            className="group relative bg-card border border-wire rounded-2xl p-5 transition-all duration-300 hover:shadow-xl hover:shadow-wire/30 hover:border-brand/40 tt"
          >
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-5">
              <div className="flex items-center gap-4">
                <div className="w-14 h-14 bg-panel rounded-2xl flex items-center justify-center border border-haze group-hover:bg-brand-muted transition-colors tt">
                  <UserIcon className="h-7 w-7 text-ghost group-hover:text-brand tt" />
                </div>
                <div>
                  <h3 className="text-lg font-bold text-ink flex items-center gap-2 tt">
                    {role === 'patient' ? `Dr. ${appointment.doctor?.name}` : appointment.patient?.name}
                    <ChevronRight className="h-4 w-4 text-slate-300" />
                  </h3>
                  <div className="flex items-center gap-2 mt-1">
                    {role === 'patient' ? (
                      <>
                        <span className="text-sm font-medium text-blue-600 bg-blue-50 px-2 py-0.5 rounded-md">
                          {appointment.doctor?.specialization}
                        </span>
                      </>
                    ) : (
                      <span className="text-sm text-slate-500">{appointment.patient?.email}</span>
                    )}
                  </div>
                </div>
              </div>
              <div className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold border ring-1 ring-inset uppercase tracking-wider ${getStatusStyles(appointment.status)}`}>
                <span className={`w-1.5 h-1.5 rounded-full ${
                  appointment.status === 'confirmed' ? 'bg-emerald-500' : 
                  appointment.status === 'cancelled' ? 'bg-rose-500' : 
                  appointment.status === 'pending' ? 'bg-amber-500' : 'bg-blue-500'
                }`} />
                {appointment.status}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 p-4 bg-panel rounded-xl mb-5 tt">
              <div className="flex items-center gap-3 text-dim tt">
                <div className="p-2 bg-card rounded-lg shadow-sm border border-haze tt">
                  <Calendar className="h-4 w-4 text-brand" />
                </div>
                <span className="text-sm font-medium">
                  {new Date(appointment.date + 'T00:00:00').toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}
                </span>
              </div>
              <div className="flex items-center gap-3 text-dim tt">
                <div className="p-2 bg-card rounded-lg shadow-sm border border-haze tt">
                  <Clock className="h-4 w-4 text-brand" />
                </div>
                <span className="text-sm font-medium">{appointment.time}</span>
              </div>
              <div className="flex items-center gap-3 text-dim tt">
                <div className="p-2 bg-card rounded-lg shadow-sm border border-haze tt">
                  <MapPin className="h-4 w-4 text-brand" />
                </div>
                <span className="text-sm font-medium truncate">Medical Center A</span>
              </div>
            </div>

            <div className="flex items-start gap-3 mb-6 px-1">
              <div className="mt-1">
                <FileText className="h-4 w-4 text-slate-400" />
              </div>
              <p className="text-sm text-dim leading-relaxed italic tt">
                &quot;{appointment.reason}&quot;
              </p>
            </div>

            {/* Shared Patient EHR Records Section for Doctor Dashboard */}
            {role === 'doctor' && (
              (() => {
                const appointmentPatientId = appointment.patientId || appointment.patient?.id;
                const patientFiles = sharedFiles.filter(f => f.patientId === appointmentPatientId);
                
                if (patientFiles.length === 0) return null;
                
                return (
                  <div className="mb-6 p-4 bg-panel rounded-2xl border border-wire/40 tt">
                    <h4 className="text-xs font-black text-ghost uppercase tracking-widest mb-3 flex items-center gap-1.5 select-none tt">
                      <FileText className="h-3.5 w-3.5 text-blue-500" />
                      Shared Patient Records ({patientFiles.length})
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {patientFiles.map((file) => (
                        <div
                          key={file.id}
                          onClick={() => {
                            setActiveFileForModal(file);
                            setCommentText(file.doctorComments || '');
                            setScanFilter('standard');
                          }}
                          className="flex items-center gap-2 px-3 py-1.5 bg-white hover:bg-blue-50 border border-slate-200 hover:border-blue-300 text-slate-600 hover:text-blue-600 rounded-xl text-xs font-bold cursor-pointer transition-all active:scale-95 shadow-sm"
                          title="Click to view details & leave comments"
                        >
                          {getFileIcon(file.category)}
                          <span className="max-w-[160px] truncate">{file.name}</span>
                          <span className="text-[10px] text-slate-400 font-semibold">• {file.size}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })()
            )}

            <div className="flex flex-wrap gap-3 pt-4 border-t border-haze tt">
              {role === 'patient' && appointment.status === 'pending' && (
                <button
                  onClick={() => onAction?.(appointment.id, 'cancelled')}
                  className="flex items-center gap-2 px-4 py-2 text-rose-600 bg-rose-50 hover:bg-rose-100 rounded-xl text-sm font-bold transition-all active:scale-95"
                >
                  <Trash2 className="h-4 w-4" />
                  Cancel Request
                </button>
              )}

              {role === 'doctor' && appointment.status === 'pending' && (
                <>
                  <button
                    onClick={() => onAction?.(appointment.id, 'confirmed')}
                    className="flex-1 flex items-center justify-center gap-2 bg-emerald-600 text-white px-4 py-2.5 rounded-xl text-sm font-bold hover:bg-emerald-700 transition-all active:scale-95 shadow-lg shadow-emerald-200"
                  >
                    <CheckCircle className="h-5 w-5" />
                    Approve Appointment
                  </button>
                  <button
                    onClick={() => onAction?.(appointment.id, 'cancelled')}
                    className="flex items-center gap-2 px-6 py-2.5 text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-xl text-sm font-bold transition-all active:scale-95"
                  >
                    <XCircle className="h-5 w-5" />
                    Decline
                  </button>
                </>
              )}

              {role === 'doctor' && appointment.status === 'confirmed' && (
                <div className="flex flex-col sm:flex-row gap-3 w-full">
                  {appointment.videoUrl && (
                    <button
                      onClick={() => router.push(`/video/${appointment.id}`)}
                      className="flex-1 flex items-center justify-center gap-2 bg-indigo-600 text-white px-4 py-2.5 rounded-xl text-sm font-bold hover:bg-indigo-700 transition-all active:scale-95 shadow-lg shadow-indigo-200"
                    >
                      <Video className="h-5 w-5" />
                      Join Video Consultation
                    </button>
                  )}
                  <button
                    onClick={() => onAction?.(appointment.id, 'completed')}
                    className={`${appointment.videoUrl ? 'sm:w-1/3' : 'w-full'} flex items-center justify-center gap-2 bg-blue-600 text-white px-4 py-2.5 rounded-xl text-sm font-bold hover:bg-blue-700 transition-all active:scale-95 shadow-lg shadow-blue-200`}
                  >
                    <CheckCircle className="h-5 w-5" />
                    Mark Completed
                  </button>
                </div>
              )}

              {role === 'patient' && appointment.status === 'confirmed' && appointment.videoUrl && (
                <button
                  onClick={() => router.push(`/video/${appointment.id}`)}
                  className="w-full flex items-center justify-center gap-2 bg-indigo-600 text-white px-4 py-2.5 rounded-xl text-sm font-bold hover:bg-indigo-700 transition-all active:scale-95 shadow-lg shadow-indigo-200"
                >
                  <Video className="h-5 w-5" />
                  Join Video Consultation
                </button>
              )}
            </div>
          </div>
        ))}
      </div>

      {/* EHR Viewer & Clinical Note Modal Overlay */}
      <AnimatePresence>
        {activeFileForModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            {/* Backdrop */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setActiveFileForModal(null)}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
            />

            {/* Modal Card */}
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              transition={{ type: 'spring', stiffness: 350, damping: 25 }}
              className="relative w-full max-w-2xl bg-card rounded-[2.5rem] shadow-2xl border border-wire overflow-hidden z-10 flex flex-col max-h-[85vh] tt"
            >
              {/* Header */}
              <div className="p-6 sm:p-8 border-b border-haze flex items-center justify-between gap-4 bg-panel/50 tt">
                <div className="flex items-center gap-3">
                  <div className="p-3 bg-blue-50 border border-blue-100 rounded-xl">
                    {getFileIcon(activeFileForModal.category)}
                  </div>
                  <div>
                    <h3 className="font-black text-ink text-lg leading-tight truncate max-w-[320px] tt" title={activeFileForModal.name}>
                      {activeFileForModal.name}
                    </h3>
                    <p className="text-slate-400 text-xs font-semibold mt-0.5">
                      {activeFileForModal.size} • {activeFileForModal.category}
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setActiveFileForModal(null)}
                  className="p-2 hover:bg-lift text-ghost hover:text-ink rounded-xl transition cursor-pointer select-none border-0 bg-transparent tt"
                  aria-label="Close modal"
                >
                  <X className="h-6 w-6" />
                </button>
              </div>

              {/* Body */}
              <div className="p-6 sm:p-8 space-y-6 flex-1 overflow-y-auto max-h-[500px]">
                {/* Inline Premium Success Toast */}
                <AnimatePresence>
                  {toastMessage && (
                    <motion.div
                      initial={{ opacity: 0, height: 0, y: -10 }}
                      animate={{ opacity: 1, height: 'auto', y: 0 }}
                      exit={{ opacity: 0, height: 0, y: -10 }}
                      className="p-3.5 bg-emerald-50 border border-emerald-200/65 text-emerald-800 rounded-2xl text-xs font-bold flex items-center gap-2 shadow-sm"
                    >
                      <CheckCircle className="h-4 w-4 text-emerald-600 animate-bounce" />
                      <span>{toastMessage}</span>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* Dynamically Rendered Clinical Report Contents */}
                {renderReportContent(activeFileForModal)}

                {/* Collapsible Decrypt Security Metadata Audit Logs */}
                <details className="group border border-wire/50 bg-panel/40 rounded-2xl overflow-hidden cursor-pointer select-none tt">
                  <summary className="p-4 flex items-center justify-between text-xs font-bold text-ghost hover:text-ink focus:outline-none tt">
                    <span className="flex items-center gap-2">
                      <Shield className="h-4 w-4 text-ghost tt" />
                      EHR Decryption & Audit Details
                    </span>
                    <span className="text-slate-400 transition-transform duration-300 group-open:rotate-180 text-[10px]">▼</span>
                  </summary>
                  <div className="px-4 pb-4 border-t border-slate-200/30 pt-3 bg-slate-900 text-slate-300 font-mono text-[10px] leading-relaxed relative overflow-hidden shadow-inner cursor-default">
                    <div className="absolute top-2.5 right-3 text-[8px] text-emerald-500 font-bold bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20">
                      Decrypted
                    </div>
                    <p className="text-blue-400 font-bold mb-1">--- DECRYPTED EHR SECURE AUDIT ---</p>
                    <p><span className="text-slate-500">Document ID:</span> {activeFileForModal.id}</p>
                    <p><span className="text-slate-500">Owner ID:</span> patient_01_nexus</p>
                    <p><span className="text-slate-500">Integrity Check:</span> SHA-256 Passed</p>
                    <p><span className="text-slate-500">Timestamp:</span> {new Date(activeFileForModal.uploadedAt).toLocaleString()}</p>
                    <p><span className="text-slate-500">Decrypted via:</span> AES-256 GCM client-side encryption key</p>
                  </div>
                </details>

                {/* Comment Section */}
                <div className="flex flex-col gap-2">
                  <label className="text-xs font-black text-ghost uppercase tracking-widest leading-none tt">
                    Clinical Comments & Notes
                  </label>
                  <textarea
                    rows={4}
                    value={commentText}
                    onChange={(e) => setCommentText(e.target.value)}
                    placeholder="Add patient instructions, dosage adjustments, or lab review notes..."
                    className="w-full bg-panel border-2 border-transparent rounded-2xl p-4 focus:bg-card focus:border-brand/20 focus:ring-4 focus:ring-brand/5 outline-none transition-all font-medium text-dim text-sm placeholder:text-ghost resize-none tt"
                  />
                  <p className="text-[10px] text-ghost font-medium leading-normal italic tt">
                    Notes saved here will show up instantly in the patient's EHR Document Vault.
                  </p>
                </div>
              </div>

              {/* Footer */}
              <div className="p-6 sm:p-8 bg-panel/50 border-t border-haze flex items-center justify-between gap-4 tt">
                <button
                  onClick={() => handleDownloadFile(activeFileForModal)}
                  className="flex items-center gap-2 px-4 py-2.5 bg-card hover:bg-panel text-dim rounded-xl text-sm font-bold border border-wire transition active:scale-95 cursor-pointer tt"
                >
                  <Download className="h-4 w-4" />
                  Download
                </button>
                <button
                  onClick={handleSaveComment}
                  disabled={isSavingComment}
                  className={`flex-1 flex items-center justify-center gap-2 ${isSavingComment ? 'bg-blue-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-500'} text-white px-5 py-2.5 rounded-xl text-sm font-bold shadow-lg shadow-blue-500/10 transition active:scale-95 cursor-pointer`}
                >
                  {isSavingComment ? (
                    <>
                      <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                      Saving...
                    </>
                  ) : (
                    'Save Comments & Sync'
                  )}
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </>
  );
}
